// <auto-generated />
using System;
using MedicalAI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalAI.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260515172802_AddMedicalClinicalTables")]
    partial class AddMedicalClinicalTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicalAI.Core.Entities.HealthCheckup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CheckupDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DoctorId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HealthCheckups", "Clinic");
                });

            modelBuilder.Entity("MedicalAI.Core.Entities.MedicalMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("ALT_SGPT")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("AST_SGOT")
                        .HasColumnType("decimal(10,2)");

                    b.Property<byte?>("Albumin_Urine")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("AlcoholConsumption")
                        .HasColumnType("bit");

                    b.Property<decimal?>("BloodGlucose")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("BloodUrea")
                        .HasColumnType("decimal(10,2)");

                    b.Property<long>("CheckupId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Cholesterol_Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<short?>("DiastolicBP")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("DirectBilirubin")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool?>("EverMarried")
                        .HasColumnType("bit");

                    b.Property<decimal?>("HbA1c")
                        .HasColumnType("decimal(4,2)");

                    b.Property<bool?>("HeartDisease_History")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Height_cm")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Hemoglobin")
                        .HasColumnType("decimal(4,2)");

                    b.Property<bool?>("Hypertension_History")
                        .HasColumnType("bit");

                    b.Property<bool?>("PhysicalActivity")
                        .HasColumnType("bit");

                    b.Property<byte?>("ResidenceType")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("SerumCreatinine")
                        .HasColumnType("decimal(5,2)");

                    b.Property<byte?>("SmokingStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Sugar_Urine")
                        .HasColumnType("tinyint");

                    b.Property<short?>("SystolicBP")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("TotalBilirubin")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Weight_kg")
                        .HasColumnType("decimal(5,2)");

                    b.Property<byte?>("WorkType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CheckupId")
                        .IsUnique();

                    b.ToTable("MedicalMetrics", "Clinic");
                });

            modelBuilder.Entity("MedicalAI.Core.Entities.PredictionResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdviceJSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CheckupId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DiseaseType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Probability")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShapValuesJSON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ThresholdUsed")
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("CheckupId");

                    b.ToTable("PredictionResults", "Analysis");
                });

            modelBuilder.Entity("MedicalAI.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "Identity");
                });

            modelBuilder.Entity("MedicalAI.Core.Entities.HealthCheckup", b =>
                {
                    b.HasOne("MedicalAI.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedicalAI.Core.Entities.MedicalMetric", b =>
                {
                    b.HasOne("MedicalAI.Core.Entities.HealthCheckup", "HealthCheckup")
                        .WithOne("MedicalMetric")
                        .HasForeignKey("MedicalAI.Core.Entities.MedicalMetric", "CheckupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthCheckup");
                });

            modelBuilder.Entity("MedicalAI.Core.Entities.PredictionResult", b =>
                {
                    b.HasOne("MedicalAI.Core.Entities.HealthCheckup", "HealthCheckup")
                        .WithMany("PredictionResults")
                        .HasForeignKey("CheckupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthCheckup");
                });

            modelBuilder.Entity("MedicalAI.Core.Entities.HealthCheckup", b =>
                {
                    b.Navigation("MedicalMetric");

                    b.Navigation("PredictionResults");
                });
#pragma warning restore 612, 618
        }
    }
}
